networks:
  inception-net:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mmouaffa/data/mariadb'  # Corriger le chemin
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mmouaffa/data/wordpress'  # Corriger le chemin

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs
      dockerfile: mariadb/Dockerfile
    env_file: ./.env
    networks:
      - inception-net
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./srcs
      dockerfile: wordpress/Dockerfile
    env_file: ./.env
    networks:
      - inception-net
    volumes:
      - wordpress_files:/var/www/html/wordpress:z
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./srcs
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      - inception-net
    volumes:
      - wordpress_files:/var/www/html/wordpress:ro,z
    depends_on:
      - wordpress
    restart: always
